pipeline {
    agent any

    tools {
        jdk
        maven 'maven 3'
    }

    stages {
        stage('GIT Checkout') {
            steps {
               
                    url: 'https://github.com/yssynhsw/DevOps-by-yssynhsw.git',
                    credentialsId: '963890'
            }
        }

        stage('Build') {
            steps {
                // Run Maven build
                bat 'mvn clean package'
            }
        }
    }
}
